<?xml version="1.0" encoding="utf-8"?>
<widget xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0"
    id="jose" version="1.0.0">
    <name>Fokus</name>
    <description>
        LA VIDA EN FOCUS.
    </description>
    <author email="jose@gmail.com" href="https://fokus.com">
        José Díaz
    </author>
    <content src="index.html" />
    <access origin="*" />
    <preference name="orientation" value="portrait" />
    <preference name="fullscreen" value="true" />
    <preference name="android-minSdkVersion" value="22" />
</widget>
